### ISSUE TITLE
\assign not recognozed in realization

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-IDE#24]
in `smglom/functional-analysis/source/mod/norm-induced-metric.en.tex` I get 
<img width="1078" alt="Screenshot 2022-09-30 at 08 35 27" src="https://user-images.githubusercontent.com/4037538/193206147-5656ffa9-cd09-4465-9dea-aee6e5ffa3d8.png">
But the `\assign` statements are there (somewhat further down).

**Comment by Jazzpirate** [comment]
The errors are real.

Note that in metric-space.en.tex, we have duplicated symbols: There are `\symdecl*`s for triangle-inequality, symmetry and identity-of-indiscernibles, and then later on `\inlineass[name=...]` with the same names.

\inlineass *generates new symbols*, so at that point we have each of those symbols twice.

You can either:
1. Delete the `\symdecl*`s and move the `(\definame{...})`s out of the \inlineass (since the symbol is only available *after* the \inlineass), or
2. Change the `name=` to `for=` in the \inlineass

**Comment by kohlhase** [comment]
Thanks, this makes sense. Did not realize the duplication. I will do 1.
