### ISSUE TITLE
linter does not pick up \inlineass[name=

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-IDE#39]
in e.g. smglom/functional-analysis/source/mod/inner-product-space.en.tex:
<img width="779" alt="Screenshot 2023-10-29 at 07 36 42" src="https://github.com/slatex/sTeX-IDE/assets/4037538/9ef7eec8-0185-4515-8ca7-40a1190be7bd">

what is worse, it even seems to mess with perfectly good `\definame`s (in the last line of smglom/logic/source/mod/derivation-relation.en.tex:)
<img width="638" alt="Screenshot 2023-10-29 at 07 47 01" src="https://github.com/slatex/sTeX-IDE/assets/4037538/d4bd1224-8f41-4619-8765-70ae6c7ddc6d">

**Comment by Jazzpirate** [comment]
I don't understand the problem...? Clearly the `\inlineass`es are being picked up on, given that they're all semantically highlighted?

> what is worse, it even seems to mess with perfectly good \definames

I don't understand what's being messed with here either...

Note however that `[name=...` *declares a new symbol* by that name, since I see both `\symdecl*{conjugate symmetry}` *and*  `\inlineass[name=conjugate symmetry]` in the first screenshot, where the latter overrides the former

**Comment by kohlhase** [comment]
OK, probably my fault.
